app.services.greeting.message: Hello World
spring:
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/company
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true

